#!/bin/bash

# This goes in /usr/bin owned by root, permissions: 755

WEBCAM_PID='x'
IP_ADDR=`ifconfig | grep "inet addr:192.168" | xargs | awk '{print $2}' | sed s/addr://`

function start_webcam() {
        raspivid -a "$IP_ADDR" -t 0 --awb incadescent --ISO 800 &
        WEBCAM_PID=$!
}

function restart_webcam() {
        kill -9 $WEBCAM_PID
        start_webcam
}

start_webcam

while [ -z "$IP_ADDR" ]; do
        sleep 1
        IP_ADDR=`ifconfig | grep "inet addr:192.168" | xargs | awk '{print $2}' | sed s/addr://`
done

restart_webcam

while [ 1 ]; do
  sleep 10 # no-op, leave process running, to not kill child processors
done
