#!/bin/bash

# This goes in /usr/bin owned by root, permissions: 755
STATE_DIR=/run/webcam_state
mkdir -p $STATE_DIR

# create named states for managing state
PID_FILE="$STATE_DIR/webcam.pid"

AWB_STATE="$STATE_DIR/awb_state"
echo "incandescent" > $AWB_STATE

ISO_STATE="$STATE_DIR/iso_state"
echo "300" > $ISO_STATE

ANNOTATION_STATE="$STATE_DIR/annotation_state"
echo "" > $ANNOTATION_STATE

function start_webcam() {
  read AWB <$AWB_STATE
  read ISO <$ISO_STATE
  read ANNOTATION <$ANNOTATION_STATE

  raspivid -a "$ANNOTATION" -t 0 --awb "$AWB" --ISO "$ISO" &
  echo $! > $PID_FILE
}

function restart_webcam() {
  pkill --signal SIGKILL --pidfile $PID_FILE
  start_webcam
}

function restart_on_setting_change() {
  read new_awb <$AWB_STATE
  read new_iso <$ISO_STATE
  read new_annotation <$ANNOTATION_STATE

  if [[ "$new_awb" != "$AWB" || \
     "$new_iso" != "$ISO" || \
     "$new_annotation" != "$ANNOTATION" ]]
  then
    restart_webcam
  fi
}

start_webcam

while true; do
  if [ "$ANNOTATION" == '' ]; then
    ifconfig | grep "inet addr:192.168" | xargs | awk '{print $2}' | sed s/addr:// > $ANNOTATION_STATE
  fi

  restart_on_setting_change
  sleep 1
done
