#!/bin/bash

# This goes in /usr/bin owned by root, permissions: 755

while [ -z "$IP_ADDR" ]; do
        sleep 1
        IP_ADDR=`ifconfig | grep "inet addr:192.168" | xargs | awk '{print $2}' | sed s/addr://`
done

raspivid -a "$IP_ADDR" -t 0 --awb incadescent --ISO 800
